name:
    CI/CID

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.6
              uses: actions/setup-python@v3
              with:
                  python-version: "3.6"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            #- name: Lint with flake8
            #  run: |
            #    # stop the build if there are Python syntax errors or undefined names
            #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Run python
              env:
                  MYSQL_USER: ${{ secrets.MYSQL_USER }}
                  MYSQL_PASSWD: ${{ secrets.MYSQL_PASSWD }}
                  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
                  MYSQL_DB: ${{ secrets.MYSQL_DB }}
              run: |
                  python utils/metadata_utils.py
            - name: Printing the metadata here
              run: |
                  cat dags/conf/tables_metadata.yaml
            #- name: Set AWS credentials
            #  uses: aws-actions/configure-aws-credentials@v1
            #  with:
            #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #      aws-region: eu-north-1
            #- name: Copy data to S3 bucket
            #  run: aws s3 sync ./dags/. s3://testmysqlbucket/dags